# $LastChangedDate: 2011-05-23 14:51:20 +0200 (Mon, 23 May 2011) $

docsdir := doc

docs:	$(docsdir)/FIM.html

$(docsdir)/FIM.html: $(docsdir)/doctags
	cd $(docsdir); ./doctags FIM.TXT > tags ; ./vim2html.pl tags FIM.TXT
	
alldocs:	docs man

man:
	cd $(docsdir); man2html fim.man >  fim.man.html
		

$(docsdir)/doctags:	$(docsdir)/doctags.o
	$(CC) -o $(docsdir)/doctags $(docsdir)/doctags.o

docsclean:
	cd $(docsdir); rm -f  doctags.o doctags FIM.html tags fim-stylesheet.css fim.man.html
	
