Document: fim
Title: Debian fim Manual
Author: <insert document author here>
Abstract: This manual describes what fim is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fim/fim.sgml.gz

Format: postscript
Files: /usr/share/doc/fim/fim.ps.gz

Format: text
Files: /usr/share/doc/fim/fim.text.gz

Format: HTML
Index: /usr/share/doc/fim/html/index.html
Files: /usr/share/doc/fim/html/*.html


